version: '3.1'

volumes:
  postgres:

services:
  server_app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_DIR_ARG=${APP_DIR}
    tty: true
    stdin_open: true
    restart: on-failure
    environment:
      RAILS_ENV: ${RAILS_ENV}
    env_file: .env
    volumes:
      - ${HOST_APP_DIR}:${APP_DIR}
      - ${HOST_APP_DIR}/vendor/bundle
    ports:
      - 3000:3000
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:3000?healthcheck=t"]
    #   interval: 5m00s
    #   timeout: 5s
    #   retries: 1
  db:
    image: postgres
    expose:
      - ${DB_PORT}
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: garage_task_development
      # POSTGRES_MULTIPLE_DATABASES: garage_task_development,garage_task_test,garage_task_production
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./docker_postgres_init:/docker-entrypoint-initdb.d
      # - ../docker-postgresql-multiple-databases:/docker-entrypoint-initdb.d
  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
        PGADMIN_DEFAULT_EMAIL: "test@gmail.com"
        PGADMIN_DEFAULT_PASSWORD: "test123!"
    ports:
        - "16543:80"
    depends_on:
        - db
