version: '3.1'

services: 
  server_app: 
    build: 
      context: .
      dockerfile: Dockerfile 
      args:
        - APP_DIR_ARG=${APP_DIR}
    # command: bash 
    tty: true 
    stdin_open: true 
    restart: on-failure 
    env_file: .env
    volumes:
      - ${HOST_APP_DIR}:${APP_DIR} 
      - ${HOST_APP_DIR}/vendor/bundle 
      - ${HOST_APP_DIR}/public/assets 
    ports:
      - 3000:3000 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000?healthcheck=t"]
      interval: 5m00s
      timeout: 5s
      retries: 1

