instance_name: project
collection_name: projects
instance_rendering_name: TODO List
collection_rendering_name: TODO LISTS

trusted_params:
  - name

index_attrs:
  - id
  - name
  - author_email

show_attrs:
  - id
  - name
  - author_email

form_attrs:
  - name
  - author_email

json_attrs:
  - id
  - name
  - author_email

has_many_assocs:
  - tasks

attrs_config:
  id:
    column_width: 50px
    name: ID
    show_method: id
