trusted_params:
  - name
  - priority
  - deadline
  - status

index_attrs:
  - name
  - priority
  - deadline
  - status

show_attrs:
  - name
  - priority
  - deadline
  - status

form_attrs:
  - name
  - priority
  - deadline
  - status

json_attrs:
  - id
  - name
  - priority
  - deadline
  - status

has_many_assocs:


attrs_config:
  id:
    column_width: 50px
    name: ID
    show_method: id
  name:
    # column_width: 200px
    name: Name
  status:
    column_width: 100px
    name: Status
  deadline:
    column_width: 100px
    name: Deadline Date
    show_method: deadline_f
  priority:
    column_width: 100px
    name: Priority
  author:
    column_width: 100px
    name: Deadline Date
