

:trusted_params:
  - :name
  - :email
  - :password
  - :password_confirmation

:index_attrs:
  - :id
  - :name
  - :email

:show_attrs:
  - :id
  - :name
  - :email

:form_attrs:
  - :name
  - :email

:json_attrs:
  - :id
  - :name
  - :email

:has_many_assocs:
  - :projects

:attrs_config:
